#ifndef VERSIONS_H
#define VERSIONS_H

#ifndef MULTIFTP_VERSION
#define MULTIFTP_VERSION "1.0"
#endif
#ifndef MULTIFTPFILE_VERSION
#define MULTIFTPFILE_VERSION "1.0.11404.09"
#endif

#endif // VERSIONS_H
